# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5f867e5642f89472a652d5ba51b155d047ff3ddee39257d76f133cad1420d9d8afe438042f84781f19de94c924b15af977b07703773e43d51e49e9695d32c7

test:
  secret_key_base: 8caeac2e2e04f85287d1a2cb8bb565ad31e7634c1413542fdf80b60517030361e368d1549ecdd6807f771060d2113d42bfee89ea40fe5beebd39c7ae6f12327a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
